
name: Labels

on: workflow_dispatch

jobs:
  main:
    name: Main
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.sha }}
    - name: Config
      uses: unity-game-framework-actions/file-access@master
      id: config
      with:
        input: |
          get:
            labels:
              input: .github/config.yml
              path: labels
    - name: Update
      uses: unity-game-framework-actions/labels-update@master
      with:
        config: ${{ steps.config.outputs.labels }}
